
---
name: "Bug report"
about: "Report bugs to improve plugin stability"
title: "Bug report"
labels: ''

body:
  - type: textarea
    attributes:
      label: "General information"
      description: "Please provide some information about what happened."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Reproducing the issue"
      description: |
      	Is there a known way the error/bug can be reproduced?
        Please provide a short list of steps you need to do to reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Proxy version"
      description: |
      	Which BungeeCord version are you using? Are you using a fork?
        Run `/bungee` on your server to check.
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Screenshots/Videos"
      description: |
      	Can you provide screenshots of the error message (if given)?
    validations:
      required: false
