name: Bug report
description: Report bugs to improve plugin stability
title: "Bug report"
labels: ["bug"]

assignees:
  - jonesdevelopment

body:
  - type: textarea
    attributes:
      label: "General information"
      description: "Please provide some information about what happened."
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
